### ISSUE TITLE
i18n.serve...(app) order.

### ISSUE THREAD

**Issue by spieglio** [i18next/i18next-node#114]
I just ran in a bunch of problems with the order in which I should add the handler and the serve...(app) things.

Here is what works for me. Maybe I have not found it but maybe this could be documented somewhere?

**Additionally:** for me the WebTranslate fails if I add anything (serveClientScript or serveDynamicResourece or any other) before it.

```
app.use(express.methodOverride());

app.use(i18n.handle);
i18n.registerAppHelper(app);
i18n.serveWebTranslate(app, {
  i18nextWTOptions: {
    // ANY SETTINGS
  }
});
i18n.serveClientScript(app);
i18n.serveDynamicResources(app);
i18n.serveMissingKeyRoute(app);
i18n.serveChangeKeyRoute(app);
i18n.serveRemoveKeyRoute(app);

# Router Setup
app.use(app.router)
```

**Comment by jamuhl** [comment]
will be different in v2: http://i18next.github.io/i18next.com/

and express middleware: https://github.com/i18next/i18next-express-middleware (replaces i18next-node)
