### ISSUE TITLE
changing language/locale for each HTTP request (express)

### ISSUE THREAD

**Issue by siddo420** [i18next/i18next-node#132]
Hi,

I am a little confused on how to set language per request using express. Here is a test code I have written that takes a long long time to load. The documentation is not so clear about this.

```
// route handler
function( req, res) {
  var locale = req.locale;
  var i18n   = req.i18n;  
  if( req.user ) {  // passport.js user
    res.write( "logged in"  );    
    i18n.setLng( req.user.locale, { fixLng: true }, function( enUS ) {
      res.write( locale );
      res.write( i18n.lng());
      res.write( i18n.t( "key" ) );    
      res.end();      
    });
  } else {
      res.write( locale );
      res.end();    
  }
}
```

I only see the text "logged in" after a long time of trying to load the page. Please let me know how to fix this or if its a bug.

Thanks.

**Comment by gauravdhiman** [comment]
As this thread is almost an year old, I hope someone raised a feature request to replace '-' with '_' or any other character in locale filenames. If it is already there, kindly point me to the required settings.

@jamuhl do you have any update on it ?

**Comment by jamuhl** [comment]
sorry for that...but no PR landed for that feature yet.
