### ISSUE TITLE
Problem with ignoreRoutes & 404

### ISSUE THREAD

**Issue by jerone** [i18next/i18next-node#151]
I've setup an app with i18next-node. As configuration options I've set the option `ignoreRoutes` to `['images/', 'public/', 'css/', 'js/', 'favicon.ico']`. All works great!

Today I added a new page that included an JavaScript file that wasn't added to the `js/` directory yet (my bad, I know). When running the page I found an 404 in the developer tool (as expected if you think about it). My problem was eventually when I tried to access that file in a new tab. Which resulted in another error `TypeError: Cannot call method 't' of undefined`. Also this error makes sense as I excluded that path in the `ignoreRoutes` option.

My 404 route is defined as following (I've translated the 404 page too):
```
app.use(function (req, res/*, next*/) {
    res.status(404);
    if (req.accepts('html')) {
      res.render('error', {
        title: req.i18n.t('error:404.title'),
        code: 404,
        message: req.i18n.t('error:404.message')
      });
    } else if (req.accepts('json')) {
      res.send({ error: 'Not found' });
    } else {
      res.type('txt').send('Not found');
    }
  });
```

Now is my question, **is it possible to keep my `ignoreRoutes` settings, _except_ when it results in an 404?**

**Comment by jamuhl** [comment]
closing...will be different in v2 i hope: http://i18next.github.io/i18next.com/

i18next-node will be replaced by https://github.com/i18next/i18next-express-middleware
