### ISSUE TITLE
HTTP Content-Language header

### ISSUE THREAD

**Issue by jerone** [i18next/i18next-node#152]
I'm wondering if this module should set the Content-Language header with the rendered language...

Some documentation:
* https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Response_fields
* http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.12

**Comment by jamuhl** [comment]
upcoming v2: http://i18next.github.io/i18next.com/

i18next-node will be replaced by https://github.com/i18next/i18next-express-middleware

PRs welcome
