### ISSUE TITLE
Initialization for i18next node sometimes hangs 

### ISSUE THREAD

**Issue by ilanle** [i18next/i18next-node#154]
Hey guys,
Thanks for this first.
I am using i18next-node version 1.7.1
I get weird behaviour, when I initialize the package, specifically when preloading language files, the whole app sometimes hangs at 100% CPU. This happens once every 20-30 restarts of the application and happens both on my localhost and on production servers.

I have two modes of operation, one is a single thread and the other is a multi-cpu setup. This happens in both. In the single thread implementation it happens and hangs the whole app. In the multi-cpu configuration it sometimes hangs just one cpu and sometimes the whole app, depending whether the master or workers are affected (this is purely statistical to my belief).

I tried to use the debug setting, and watched the output logs, they list the names of the language files loaded during preload. 

currentLng set to: en
loaded file: locales/translation-en.json
loaded file: locales/translation-es.json
loaded file: locales/translation-de.json
loaded file: locales/translation-fr.json
loaded file: locales/translation-simple.json
loaded file: locales/translation-ru.json
loaded file: locales/translation-ar.json
loaded file: locales/translation-he.json
loaded file: locales/translation-pt.json
loaded file: locales/translation-nl.json
loaded file: locales/translation-pl.json
loaded file: locales/translation-it.json
12:53:18 info   listening on port 3000

When the system hangs, it consistently hangs before the file names are logged (right after "currentLng set to:en")

Here is the code for initializing the package:

	i18nOptions =
		fallbackLng: 'en'
		debug: true
		resGetPath: 'locales/__ns__-__lng__.json'
		preload: langUtils.translatedLanguages
		ignoreRoutes: ['css/', 'img/', 'js/', 'lib/']
		detectLngFromPath: false
		detectLngFromHeaders: false
		forceDetectLngFromPath: false
		saveMissing: true
		shorcutFunction: 'defaultValue'

	i18n.init i18nOptions, ()->
            Do stuff

Where langUtils.translatedLanguages ==   [ 'en',  'simple',  'es',  'de',  'fr',  'ru',  'he',  'ar',  'nl',  'pl',  'pt',  'it' ]

Any ideas?

Thanks,
Ilan

**Comment by ilanle** [comment]
This definitely happens to me as well.
I have seen it many times before, and I have been able to reproduce it both on a production server and locally on my machine.
It is true that it is not deterministic and cannot be reproduced on demand, but I find that since it completely hangs the cpu, I can reproduce it by setting a server restart to run every time a successful init happens, this means that after a few minutes of restarts, the code hangs. 
I was able by logs to corroborate that the code hangs exactly at i18n init.
In the code below the app will hang after "init app 1".

I use version 1.7.1 of i18next

**Will happily make myself available for testing. I am running a production grade site and I am jumping through hoops right now to work around those hangups**

Cheers,
Ilan


```javascript

	app = express()
	i18nOptions =
		fallbackLng: 'en'
		debug: false
		resGetPath: 'locales/__ns__-__lng__.json'
		ignoreRoutes: ['css/', 'img/', 'js/', 'lib/']
		detectLngFromPath: false
		detectLngFromHeaders: false
		forceDetectLngFromPath: false
		saveMissing: true
		shorcutFunction: 'defaultValue'
	logger.info null, "init app 1"

	i18n.init i18nOptions, ()->
		logger.info null, "init app 2"
```javascript

**Comment by ilanle** [comment]
Oh snap !!
This was my own issue to begin with. I totally forgot posting it.
Anyway,
I can now reproduce it, so I am available to carry out any testing.
Looking forward to resolve this.

**Comment by ilanle** [comment]
More specifically, this is where it hangs: 
( i8next-1.7.1.js line 660 )

```javascript
        // else load them
        
        i18n.sync.load(lngsToLoad, o, function(err, store) {
            resStore = store;
            initialized = true;
    
            if (cb) cb(lngTranslate);
            if (deferred) deferred.resolve(lngTranslate);
        });
```javascript

**Comment by jamuhl** [comment]
to be honest...i have no idea yet what's happening...but this must get solved for sure.

**Comment by ilanle** [comment]
Thanks for responding.
I am carrying out some more testing right not.
I could now be more specific as to the exact place in code where this happens.
This actually happens in filesync.js, under method fetchOne.
The line
 fs.readFile(filename, 'utf8', function(err, data)  just hangs.

It does not return an error or data, just hangs the cpu at 100%.
I am not sure at all that this is a problem with your library, but it does always hang at the same location.
I have removed the preload command from my code, so right now it loads only a single language file which is the current language on init.

It hangs once every 50 attempts or so

**Comment by ilanle** [comment]
Another detail - I have upgraded i18next to latest version (1.10.3) and this still happens

**Comment by ilanle** [comment]
Another update,
I have found a workaround.

It seems that fs.readFile is what kills the system, for an unknown reason.
However I found that when I replace it with a synchronous file read, it works fine and I can confirm that the system does not hang up any more.
Here is my revised code for fetchOne, FYI
I guess this happens to no one else, so you can close this


```javascript
  fetchOne: function(lng, ns, cb) {

        var filename = this.functions.applyReplacement(this.options.resGetPath, {lng: lng, ns: ns});
        var self = this;
        var data = fs.readFileSync(filename, 'utf8');
        if (!data){
            return cb("error reading file")
        }else{
            self.functions.log('loaded file: ' + filename);
            try {
                var result = path.extname(filename) === '.json5' ?
                    JSON5.parse(data.replace(/^\uFEFF/, '')) :
                    JSON.parse(data.replace(/^\uFEFF/, '')) ;// strip byte-order mark
            }
            catch (err) {
                err.message = 'error parsing ' + filename + ': ' + err.message;
                return cb(err);
            }
            cb(null, result);
        }
        //fs.readFile(filename, 'utf8', function(err, data) {
        //    if (err) {
        //        cb(err);
        //    } else {
        //        self.functions.log('loaded file: ' + filename);
        //
        //        try {
        //            var result = path.extname(filename) === '.json5' ?
        //                JSON5.parse(data.replace(/^\uFEFF/, '')) :
        //                JSON.parse(data.replace(/^\uFEFF/, '')) // strip byte-order mark
        //        }
        //        catch (err) {
        //            err.message = 'error parsing ' + filename + ': ' + err.message;
        //            return cb(err);
        //        }
        //        cb(null, result);
        //    }
        //});
    },
```javascript

**Comment by jamuhl** [comment]
hm...strange but glad you found a workaround. Closing this for now.
