### ISSUE TITLE
Testing the Turkish "I" Problem

### ISSUE THREAD

**Issue by marcellodesales** [i18next/i18next-node#157]
Hi there,

Could you please help me understand if I'm using the library correctly? I'm trying to build a module to verify i18n apps and if they pass the Turkish Problem... As described at http://blog.codinghorror.com/whats-wrong-with-turkey/... The code encoding values are located at http://en.wikipedia.org/wiki/Dotted_and_dotless_I

Should the library be responsible for translating those cases???

Requirement
=======

Operations over the strings must result in correct values. When locale is set to the Turkey locale "tr_TR", the result should be:

```js
"INTEGER".toLowerCase() = "ınteger" // the first characters is &#305;  
"integer".toUpperCase() = "İNTEGER" // the first character is &#304;
```

The complete list of characters is at http://webdesign.about.com/od/localization/l/blhtmlcodes-tr.htm

Attempt
====

```js
> var i18n = require("i18next");
> i18n
{ version: '1.7.4',
  clientVersion: '1.7.3',
...
> i18n.setLng("tr-TR")
> i18n.lng()
'tr-TR'
> i18n.t("integer").toUpperCase()
'INTEGER'
> "INTEGER".split("").map(function(char) { return char.charCodeAt(0); });
[ 73,
  78,
  84,
  69,
  71,
  69,
  82 ]
> i18n.t("INTEGER").toLowerCase()
'integer'
> "integer".split("").map(function(char) { return char.charCodeAt(0); });
[ 105,
  110,
  116,
  101,
  103,
  101,
  114 ]
```

Expected
====

Here are the tests I ran to verify what the output would be. Notice that the character decimal should be completely different. The values are in the table at http://en.wikipedia.org/wiki/Dotted_and_dotless_I

```js
> "İNTEGER".split("").map(function(char) { return char.charCodeAt(0); });
[ 304,
  78,
  84,
  69,
  71,
  69,
  82 ]
> "ınteger".split("").map(function(char) { return char.charCodeAt(0); });
[ 305,
  110,
  116,
  101,
  103,
  101,
  114 ]
> 
```

**Comment by marcellodesales** [comment]
Hi @jamuhl, 

```
i18next.toUpperCase(str, LOCALE_CODE)
i18next.toLowerCase(str, LOCALE_CODE)
```

This one would definitely help... Since this is a NODE module, I would not expect to depend on any external value, including the one in the browser's reference.

In addition, maybe someone like myself would want to override the string methods above in my custom app... I just hope this is feature supported by any i18n String, no matter which language it is.

thanks!

**Comment by jamuhl** [comment]
i see your arguments...i would be glad to accept any PR regarding this topic...
