### ISSUE TITLE
i18n express routes not working

### ISSUE THREAD

**Issue by Looney77** [i18next/i18next-node#164]
Hi,

I'm currently facing a problem with i18next-node. 

When the frontend requests any of the i18next routes, express responds a 404.

For example, the i18n.serverClientScript(app) is called well, and also checked with a console.log(app._router.stack) the route is well registered, but when /i18next/i18next.js is called, it fails to load. The same for /locales/ressources.json?lng=en&ns=translation and i18next webTranslate.

Any idea ?

I'm using Express v4.10.6, here below is my app.js for example :

<code>
i18n.init({
    lng: 'en',
    preload: ['en', 'fr', 'nl'],
    fallbackLng: 'en',
    saveMissing: true,
    sendMissingTo: 'en',
    debug: true,
    useCookie: false,
    detectLngFromHeaders: false,
    ns: {
      namespaces: ['translation'],
      defaultNs: 'translation'
    }
  });

var app = express();

require('./config/express')(app, config, i18n); // Here is i18n.handle(app); just after template load and before the controller is declaring the routes

i18n.registerAppHelper(app);
i18n.serveClientScript(app)
  .serveDynamicResources(app)
  .serveMissingKeyRoute(app);
</code>

Thanks a lot,

Looney

**Comment by jamuhl** [comment]
you ever checked out the sample: https://github.com/i18next/i18next-node/tree/master/sample

does that work for you?

**Comment by Looney77** [comment]
Hi,

Thanks for reply, of course I've checked this one, and it's working, that's why I'm not really understanding what I'm doing wrong, except that I configure the express via a separate module.

I've now bypass the module, and inserted it in the app.js directly, but still not working : 

Here is my app.js.
```
var express = require('express');
var glob = require('glob');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var compress = require('compression');
var methodOverride = require('method-override'),
  config = require('./config/config'),
  db = require('./app/models'),
  demo = require('./demodata'),
  i18n = require('i18next');


i18n.init({
    lng: 'en',
    preload: ['en', 'fr', 'nl'],
    fallbackLng: 'en',
    saveMissing: true,
    sendMissingTo: 'en',
    debug: true,
    useCookie: false,
    detectLngFromHeaders: false,
    ns: {
      namespaces: ['translation'],
      defaultNs: 'translation'
    }
  });

var app = express();

// require('./config/express')(app, config, i18n);

app.use(i18n.handle);
app.set('views', config.root + '/app/views');
app.set('view engine', 'jade');


app.set('title', 'My Title');

app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
  extended: true
}));

app.use(cookieParser());
app.use(compress());
app.use(express.static(config.root + '/public'));
app.use(methodOverride());

var controllers = glob.sync(config.root + '/app/controllers/*.js');
controllers.forEach(function (controller) {
  require(controller)(app);
});

app.use(function (req, res, next) {
  var err = new Error('Not Found');
  err.status = 404;
  next(err);
});

if(app.get('env') === 'development'){
  app.locals.pretty = true;
  app.use(function (err, req, res, next) {
    res.status(err.status || 500);
    res.render('error', {
      message: err.message,
      error: err,
      title: 'error'
    });
  });
}

app.use(function (err, req, res, next) {
  res.status(err.status || 500);
  res.render('error', {
    message: err.message,
    error: {},
    title: 'error'
  });
});

i18n.registerAppHelper(app);
i18n.serveClientScript(app)
  .serveDynamicResources(app)
  .serveMissingKeyRoute(app);

db.sequelize
  .sync()
  .complete(function (err) {
    if(err){
      throw err[0];
    }else{
      if(config.demodata) {
        demo.setData();
      }
      app.listen(config.port);
    }
  });
```

Br,

Looney

**Comment by Looney77** [comment]
Hi again,

I've found my problem, serverClientScript must be called before other routes are defined, that where was my problem.

Thanks,

Looney

**Comment by jamuhl** [comment]
glad you found it
