### ISSUE TITLE
Question serveClientScript

### ISSUE THREAD

**Issue by sylbal** [i18next/i18next-node#166]
Hi,
A newbie question about server/client usage of i18next.
I have implemented i18next in the node app and integrate with jade template, great stuff, worked like a charmed as described in the doc.
Then I need to do some i18n on the client side, I've used the serveClientScript feature and it works great but it's served as unminimified js.
Is there a way to serve it miniminied ? For production use, should I not use the "client specific" library instead of the serveClientScript stuff ?
Any tips on best practice is welcome, thank's

**Comment by jamuhl** [comment]
setting NODE_ENV=production will serve the minified version and add cache headers:

`NODE_ENV=production node myApp.js`

(https://github.com/i18next/i18next-node/blob/master/lib/i18next.js#L149)

**Comment by sylbal** [comment]
Thank's a lot for this quick answer and solution.
