### ISSUE TITLE
cache control header is not well formed

### ISSUE THREAD

**Issue by lcalvy** [i18next/i18next-node#169]
Hi, 
cache control header is missing a comma between cache location (public, private,...) and cache duration (max-age).

Even if RFC is not clear about the mandatory of using a comma, it's used to be indicated in header.
http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html

This is a severe problem with cloudflare (nginx?) that seem's doesn't cache if comma is missing

**Comment by jamuhl** [comment]
merged - will publish new version to npm this week
