### ISSUE TITLE
Is it possible to use regular strings as JSON keys?

### ISSUE THREAD

**Issue by luileito** [i18next/i18next-node#171]
Hi, I'm missing the possibility of using full strings in the resource json files, e.g.:
```javascript
{
  ...
  "I'm a full string. Also notice the dots.": "This is the translated text",
  ...
}
```
So they can be used "as is" in the templates, e.g. in handlebars:
```
<title>{{t "I'm a full string. Also notice the dots."}}</title>
```

Can it be done? Will it be possible?

Thx in advance, 
Luis

**Comment by jamuhl** [comment]
sure...on init override:

```
    nsseparator: ':',
    keyseparator: '.',
```

to something not occuring in regular text, eg: '::' and '..'

**Comment by luileito** [comment]
You're right. It passed unnoticed while reading the docs. Thanks!

**Comment by jamuhl** [comment]
not your fault...the documentation needs some major overhaul...hope to be able to invest time for this soon.

meanwhile...keep asking if you encounter any problem.

**Comment by lcustodio** [comment]
Keep in mind that for the current version (v3.3.1), the configuration has changed:

The keys are: `nsSeparator` and `keySeparator`

http://i18next.com/docs/options/

**Comment by jamuhl** [comment]
hm...should mention this values can be set to `false` nowadays: http://i18next.com/translate/keyBasedFallback/
