### ISSUE TITLE
Handling unknown languages via addRoute in Express

### ISSUE THREAD

**Issue by luileito** [i18next/i18next-node#173]
Hi, I'm playing with the SEO-friendly routes in Express. If I preload N langs on init, can `i18n.addRoute` handle routes for non-preloaded langs? It seems not to fall back to the default lang; for instance:

```javascript
var allowLangs = ['en', 'es'];
i18n.init({
  lng: allowLangs[0],
  fallbackLng: allowLangs[0],
  preload: allowLangs
}, function onLoad(t){
  i18n.addRoute('/:lng/routes.some', allowLangs, router, 'get', getSomePage);
});
```

If the user requests a non-preloaded lang, say `/fr/some`, the route seems not to be available, however I'd expect `getSomePage` to be executed with 'en' as fallback. Is there any option to cope with this issue? Right now I only can think of explicitly defining `router.get('/:lng/some', ...)` in the app. 

Thx, 
Luis

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-node/blob/master/lib/i18next.js#L304 does the trick.

adding some init option to stop that behaviour would be all it takes...will add this for next version - or a PR would be welcome.

**Comment by luileito** [comment]
Ok, thanks for the clarification. I just submitted the PR https://github.com/i18next/i18next-node/pull/174
