### ISSUE TITLE
Problem with pluralExtensions inside detectLanguageFromPath 

### ISSUE THREAD

**Issue by eruanntion** [i18next/i18next-node#175]
Hi,

My team and I had some issues today when we tried to prepare Albanian localization for our project. We set i18n to detect language from path, and we set 'al' as Albanian country code. For every other language app worked just fine, but not for Albanian. Later on, by inspecting the source of /lib/dep/i18next.js, we found that country code for Albanian is set to 'sq'. 

Although this solved our issue, it was bugging me why can't we use short codes we like. Then I noticed that when I set language with query string ( setLng=al in our case) resource loads just fine, but the same won't work by using detection from path. Further on, by expecting detectLanguageFromPath, I noticed these lines of code:

var lookUp = wrapper.pluralExtensions.rules[part.split('-')[0]];
if (lookUp) locale = part;

Obviously, since 'al' has no pluralExtension rule, language never get set. At the same time, none of the other methods for language detection (detectLanguageFromQuerystring, detectLanguageFromCookie, detectLanguageFromHeader) don't have pluralExtension check, and that's the reason why they work.

Possible workaround for our problem would be:

i18n.pluralExtensions.addRule("al", {}); //or any other custom code 

... but it seams to me as unnecessary code, especially considering that we never use plural extensions.

**Comment by jamuhl** [comment]
official code for albanian is 'sq' (http://www.w3schools.com/tags/ref_language_codes.asp) - why you want some custom value?

**Comment by eruanntion** [comment]
Hi Jan,

Thnx for the answer. To answer to your question, this was actually request from our clients, to use "al" as albanian shortcode instead of "sq". So, when we used language switching with any other method (querystring, cookie etc), it worked, but not with path detection. 

As you suggested, I made a pull request, so if you agree, you could make a merge :)

**Comment by jamuhl** [comment]
PR was merged...new version will be published this week
