### ISSUE TITLE
Package unable to handle multiple locale names for simplified Chinese locale.

### ISSUE THREAD

**Issue by jdbennet2001** [i18next/i18next-node#176]
There are multiple ways to specify simplified Chinese in IE11; zh-Hans, zh-Hant, zh, zh-cn. There doesn't seem to be a way to map multiple locale names to the same translation file. The only way to support this seems to be to create multiple directories, one for each language.

There should be a way to indicate that multiple locales all map to the same translation file.

**Comment by jamuhl** [comment]
would be doable by extending https://github.com/i18next/i18next/blob/master/src/i18next.helpers.js#L431

as i'm on the run to release next version - i'm not sure if this will land in this version.

a PR adding this would be very welcome.

**Comment by jamuhl** [comment]
upcoming v2: http://i18next.github.io/i18next.com/

i18next-node will be replaced by https://github.com/i18next/i18next-express-middleware

PRs welcome
