### ISSUE TITLE
resGetPath not working

### ISSUE THREAD

**Issue by kenkouot** [i18next/i18next-node#177]
I'm having an issue where calling init and specifying `resGetPath` is not actually working. 

Here was what my initialization looks like:
```typescript
i18n.init({
  resGetPath: path.join(__dirname, '..', 'front/locales/__lng__/__ns__.json'),
  supportedLngs: ['en', 'de'],
  fallbackLng: 'en',
  detectLngFromPath: false,
  detectLngFromHeaders: false
}, (t) => {
  console.log(t('app:key'));
}
```
Note, that if I pass in a properly formed object to resStore, then the translations will succeed.

**Comment by jamuhl** [comment]
try setting debug: true for init options...rather sure something with path is wrong.

**Comment by kenkouot** [comment]
figured it out, thanks :dancer:
