### ISSUE TITLE
Typo on i18next-node documentation

### ISSUE THREAD

**Issue by nikkow** [i18next/i18next-node#179]
Hi,

Just spotted a typo in the "features" page of i18next-node website (http://i18next.com/node/pages/doc_features.html). The last example about saving missing resources to translation files states:

```javascript
var option = { 
  // change path to store file
  resSetPath: 'locales/__lng__/__ns__.json';
 
  // send missing values to
  sendMissingTo: 'fallback|current|all'
};
```

It should instead be:

```javascript
var option = { 
  // change path to store file
  resSetPath: 'locales/__lng__/__ns__.json',
 
  // send missing values to
  sendMissingTo: 'fallback|current|all'
};
```

(Note the ";" replaced by ",").

**Comment by jamuhl** [comment]
thanks for reporting....will fix this asap.

**Comment by jamuhl** [comment]
fixed...thanks again for reporting.
