### ISSUE TITLE
Generate urls <link rel="alternate" hreflang >

### ISSUE THREAD

**Issue by laurentdebricon** [i18next/i18next-node#186]
Hello i would like to generate the <link rel="alternate" href="http://example.com/fr-be" hreflang="fr-be" />  https://support.google.com/webmasters/answer/189077
for all the languages supported in my html.

I have localized routes /:lng/my.trad/my.trad2
I tried to create a middleware generateLinksAlternate(req, res, next)
but sadly inside I don't have access to the string '/:lng/my.trad/my.trad2' used when I did 
	`i18n.addRoute('/:lng/my.trad/my.trad2`
but only the route string already translated

Any thoughts ?

**Comment by jamuhl** [comment]
do i get it right? when eg: `/en/some/translatedStuff` you want to know the routes origin expression that was `/:lng/key1/key2`?

if so overload the `i18n.addRoute` function by adding an additional middleware on line 304 appending the route param to the request.

**Comment by laurentdebricon** [comment]
Perfect 

```javascript
var supportedLngs = ['en','fr','es'];
```

edit : i18n.addRoute :
```javascript
app[verb || 'get'].apply(app, [locRoute.join('/'), ensureIsSupportedLanguage(lngs), saveOriginalRoute(route)].concat(callbacks));
```
and put the function  i18n.addRoute in your express file (with the function ensureIsSupportedLanguage because addRoute needs it)

```javascript
function saveOriginalRoute(route) {
	return function(req, res, next) {
		req.route.notTranslated = route;

		return next();
	};
}
```

```javascript
	function generateLinksAlternate(req, res, next) {
		var notTranslated = req.route.notTranslated;

		if (notTranslated.indexOf('/:lng') != -1) {
			var html = "";
			for (var i = 0; i < supportedLngs.length; i++) {
				var language = supportedLngs[i];

				// code piqué dans i18next
				var parts = notTranslated.split('/');
				var locRoute = [];
				for (var y = 0, ly = parts.length; y < ly; y++) {
					var part = parts[y];
					if (part.indexOf(':') === 0) {
						if (part == ":lng") {
							locRoute.push(language);
						} else {
							locRoute.push(req.params[part.substring(1)]);
						}

					} else {
						locRoute.push(i18n.t(part, {
							lng: language
						}));
					}
				}

				html += '<link rel="alternate" href="https://www.mywebsite.com' + locRoute.join('/') + '" hreflang="' + language + '" />\n';
			}

			res.locals.linkAlternate = html; // you can now access in your view directly the var linkAlternate
		}

		return next();
	}
```

and when you add one route, you call the middleware generateLinksAlternate
```javascript
i18n.addRoute('/:lng/my.trad/my.trad2', supportedLngs, app, 'get', generateLinksAlternate, routes.index);
```

this is a solution for the issue https://github.com/i18next/i18next-node/issues/172
Thank you
