### ISSUE TITLE
setLng and express-session (?)

### ISSUE THREAD

**Issue by prtome** [i18next/i18next-node#192]
Hello - sorry if it is not the correct place to ask this question, but I am stuck since a few days.
I am afraid this is very basic, but I don't understand why it doesnot work like I see everywhere
I am using node and express(just installed on new computer) . I init i18next without a lang. My route checks a database and returns the lang for that route. Thus I do:
req.i18n.setLng(defaultLang);
console.log(defaultLang, req.i18n.lng());  returns fr-FR en-US (the lang chosen, my browser lang). 
I thought it would be fr-FR twice.
The page is rendered in the fallback language IT (i have filled the locales for italian and french only)
This happens when I connect the first time after I started the server. Then I chose another route, this one returns italian as language. OK page rendered in Italian. 
I go back to the french route - et voila, page in french. 
From now on, no more translation problems.
restart the server, start with the italian route,and top get the french page translated  I have to do : italian, french (and no translation) , italian, french (and now OK)
Why ? what is going on ? why the first time it does not work ? 
I use express-session with mongo-store, https, csruf, jade. There is not much in the application for now. 
Thanks for any pointer 
p.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-node/blob/master/lib/i18next.js#L94

setLng sets lng to `req.lng`

req.i18n.lng() returns the locale found by i18next not the one set by the setLng function.

t function takes lng first from req.lng. https://github.com/i18next/i18next-node/blob/master/lib/i18next.js#L84

might be some async issue that fr resources are not loaded on first access, could you try:

`i18n.init({ preload: ['it', 'fr'] });`

**Comment by prtome** [comment]
Ok I understand then why req.i18n.lng() always returns my browser lang.  In the rest of my  code I use req.lng

and yes, preloading the langs in init solves the problem.
I was working on a very old laptop with ubuntu and having no problem. I moved to a Mac, and it did not work. So there must be some difference. Thanks for solving my problem.

**Comment by jamuhl** [comment]
you're welcome...feel free to reopen this or to create a new issue on any new problem regarding i18next.
