### ISSUE TITLE
i18next multiple json packages

### ISSUE THREAD

**Issue by Minbozz** [i18next/i18next-node#194]
I have a question how should i initialize or configure the i18next in order to use split the ns.special.json file into several .json files?

**Comment by jamuhl** [comment]
http://i18next.com/pages/doc_init.html --> options to load resources ---> Multiple namespace

```
var option = { 
ns: { 
    namespaces: ['app', 'buttons'], 
    defaultNs: 'app'
  } 
};
 
i18n.init(option, function(t) {
  // access default namespace
  var x = t("any.key.from.app")
 
  // to access another namespace prepend [ns]:
  var y = t("buttons:any.key.from.buttons") 
});
```

**Comment by Minbozz** [comment]
thank you very much :+1:
