### ISSUE TITLE
Multiple handler on addRoute function

### ISSUE THREAD

**Issue by zauker** [i18next/i18next-node#195]
I need SEO friendly routes, so i'm using the addRoute function.
There is a problem, in Express routing i can use multiple handler per route:

i.e. can i use two handler

    app.get('/my/route', isLoggedIn, function(req, res) {
    });

There is a way to do that with i18next-node addRoute or it is not possible?

**Comment by jamuhl** [comment]
was added some time ago: https://github.com/i18next/i18next-node/blob/master/lib/i18next.js#L295

**Comment by zauker** [comment]
thanks @jamuhl for your reply.

so this code:

    app.get('/signup', isLoggedIn, isValidUser, function(req, res) {
      some code here
    });

need to be rewrite as:

    i18n.addRoute('/:lng/main:pages.signup.route', ['en', 'it', 'de', 'fr'], app, 'get', [isLoggedIn, isValidUser, signupHandler]);

    var signupHandler = function(req, res){
      some code here
    }

right?

**Comment by jamuhl** [comment]
`i18n.addRoute('/:lng/main:pages.signup.route', ['en', 'it', 'de', 'fr'], app, 'get', isLoggedIn, isValidUser, signupHandler);` should work too.
