### ISSUE TITLE
Semvar violations

### ISSUE THREAD

**Issue by donniev** [i18next/i18next-node#198]
Please stop using only increases in the minor version when you have breaking changes. This cost our team several hours tracking it down. It is not sufficient to just note it in the changelog. The semver convention is that breaking changes should increment the major version not the minor version.

**Comment by donniev** [comment]
actually semver not semvar, of course.

**Comment by jamuhl** [comment]
will be better starting from upcoming v2.0.0 (1.x.x will be closed soon)
