### ISSUE TITLE
remoteSync: saveMissing use resSetPath, not resPostPath

### ISSUE THREAD

**Issue by nikkow** [i18next/i18next-node#201]
Hi, 

I just spotted what seems to be a mistake in the "remoteSync" backend explanation on this page: http://i18next.com/node/pages/doc_init.html

I've copied/pasted the config described there, replaced it with my URLs and didn't manage to get it working. After some investigation, the `saveMissing` method in `sync.js` never uses the described `resPostPath`, but uses `resSetPath` instead. 

Either the `sync.js` (line 96) should be corrected:
```javascript
var url = this.functions.applyReplacement(this.options.resSetPath, {lng: lng, ns: ns})
```
should become
```javascript
var url = this.functions.applyReplacement(this.options.resPostPath, {lng: lng, ns: ns})
```

Or the doc should be adapted.

**Comment by jamuhl** [comment]
sorry...yes...the documentation is wrong...should be `this.option.resSetPath`. Will update documentation asap. sorry again for the trouble caused.

**Comment by nikkow** [comment]
No problems :) Just wanted to let you know! Thanks!

**Comment by jamuhl** [comment]
will be correct in v2: http://i18next.github.io/i18next.com

https://github.com/i18next/i18next-node-remote-backend
