### ISSUE TITLE
MongoDB backend fails to initialize

### ISSUE THREAD

**Issue by buehler** [i18next/i18next-node#205]
Hey there

I experienced a strange error with the mongodb backend for i18next:

Error: collection name must be a String
at Error (native)
at checkCollectionName (node_modules/i18next.mongoDb/node_modules/mongodb/lib/utils.js:69:11)
at new Collection (node_modules/i18next.mongoDb/node_modules/mongodb/lib/collection.js:57:3)

I checked it, and the part where "new mongo.Collection" us used, seems to use wrong parameter.

for which version of the mongodb driver was this package built? Is there any chance for a fix / quickfix?

Cheers
Chris

**Comment by jamuhl** [comment]
might be that this needs changes for current mongodb driver api. right, now i'm working fullspeed on a complete rewrite of i18next to v2.0.0 so changes to get this fixed soon are rather low.

best way to get this fixed would be a PR.

**Comment by buehler** [comment]
Hey @jamuhl 
Alright, as soon as I'm working with this problem again, I'll create a PR
;)

Cheers

**Comment by jamuhl** [comment]
great...thank you.

**Comment by kcaron-cst** [comment]
@buehler Just curious if you happened to end up using the `i18next.mongoDb` module or if you went by another approach. Researching options for a i18next + mongodb integration.

**Comment by buehler** [comment]
Hey @kcaron-cst 
Well I was planning to fix the mongodb module, but actually I had no time in my actual project to fix it. It will be an issue in the near future, but at this point I have no ETA :neutral_face:

**Comment by jamuhl** [comment]
please take note of upcoming v2 of i18next http://i18next.github.io/i18next.com/

backends will be easier to create and include. http://i18next.github.io/i18next.com/docs/ecosystem/#backends

closing for now
