### ISSUE TITLE
How do I create custom detectLanguage function\middleware?

### ISSUE THREAD

**Issue by stian-sandvold** [i18next/i18next-node#206]
I currently have 2 domains, a x.se and x.no. Simple enought, I want .se domain to have swe language and .no domain to have nor language.

I tried to create a middleware which is added right after I init i18n, which checks hostname for the occurences of the spesific names. I tried setting both req.locale and i18n.setLng('se', next) but it only uses my main\fallback language: 'no'.

Is there a better way to create my own custom function to detect language? Or what should the common practice be here?

- Thanks

**Comment by jamuhl** [comment]
you need to append your middleware after `app.use(i18n.handle);` and set req.lng.

or add `detectLanguageFn(req, res) -> returns locale string` to init options.

**Comment by jamuhl** [comment]
closing...please take not of i18next v2 (beta: http://i18next.github.io/i18next.com/) and the new https://github.com/i18next/i18next-express-middleware
