### ISSUE TITLE
Error when trying to pluralise

### ISSUE THREAD

**Issue by ApfelUser** [i18next/i18next-node#208]
I am getting:

```log
key 'main:section.join (en)' returned an object instead of string. 
```

My **locales/en/main.json** file:

```json
{
  "section": {
    "join": {
      "key": "Text __onlinePlayers__ text",
      "key_plural": "Text __onlinePlayers__ text"
    }
  }
}
```

**Comment by jamuhl** [comment]
access plural like: `i18n.t('main:section.join.key', {count: 10});`

**Comment by ApfelUser** [comment]
@jamuhl when I do that it always just takes the **key**. Also if **__onlinePlayers__ > 1**.

**Comment by jamuhl** [comment]
the passed in option needs to be count for the plural so:

a)
```
{
  "section": {
    "join": {
      "key": "Text __count__ text",
      "key_plural": "Text __count__ text"
    }
  }
}
```

or b)
i18n.t('main:section.join.key', {count: 10, onlinePlayers: 10});

**Comment by ApfelUser** [comment]
Thanks a lot! The option to use custom variable names as feature would be nice. Because I can imagine that I'll need to make more than 1 string pluralisable in the future.
