### ISSUE TITLE
Dynamic routes render on any URL

### ISSUE THREAD

**Issue by lenovouser** [i18next/i18next-node#209]
I have this code:

```javascript
i18n.init({
   ns: 'main',
   resGetPath: 'locales/__lng__/main.json',
   fallbackLng: 'en',
   saveMissing: true,
   debug: debug,
   escapeInterpolation: false,
   sendMissingTo: 'en',
   detectLngQS: 'language',
   detectLngFromPath: 0,
   supportedLngs: Config.get('languages'),
   preload: Config.get('languages'),
   cookieName: '_tld.domain.language',
   cookieDomain: '*.domain.tld'
   }, function(t) {
      i18n.addRoute('/:lng/team/', Config.get('languages'), app, 'get', Controllers.team);
      i18n.addRoute('/:lng/legal/', Config.get('languages'), app, 'get', Controllers.legal);
      i18n.addRoute('/:lng/', Config.get('languages'), app, 'get', Controllers.home);
      app.get('*', function(req, res) {
         res.status(404).send('404: Page not Found');
      });
});
```

My problem basically is that **i18next-node** is not only listening on e.g. `/:lng/`, but also on `/gfwiefgiqegfhqifh/` and rendering the homepage there. After a lot of testing I guess this is a bug. Or am I doing something wrong?

**Comment by jamuhl** [comment]
you can use https://github.com/i18next/i18next-node/blob/master/lib/i18next.js#L314

in combination with the ensureSupportedLanguage Middleware on line 325

**Comment by ApfelUser** [comment]
This doesn't fix everything I think.

I now added

```javascript
ensureLngSupport: true
````
to the configuration.

Basically what it does now is:

`/en/team` (**200**) :+1:
`/en/team/xxx` (**404**) :+1:
`/` (**200**) :+1:
`/xxx` (**200**, should be **404**) :-1:
`/en/` (**404**, should be **200**) :-1:

Hope this isn't too hard to understand.

**Comment by jamuhl** [comment]
`i18n.addRoute('/:lng/'` will result in `/en` route not `/en/`

why `/xxx` is allowed idk.

**Comment by jamuhl** [comment]
might need to add some more test cases here: https://github.com/i18next/i18next-node/blob/master/test/i18next.server.spec.js#L40 but on holiday right now...so not sure i get to it right now.

**Comment by ApfelUser** [comment]
Hm. `/de` and `/de/` do render, but in English, not German. Thats why I think that something is buggy because after the `/` everything is allowed and it renders over the `Controller.home`.

**Comment by jamuhl** [comment]
not sure...https://github.com/i18next/i18next-node/blob/master/test/i18next.server.spec.js#L70 tests this and tests are ok...but might be i miss something in the test cases.

**Comment by ApfelUser** [comment]
I tested a bit more, and broke it down to one line:

with 

```javascript
ensureLngSupport: true
```

the code which is causing this is:

```javascript
i18n.addRoute('/:lng/', Config.get('languages'), app, 'get', Controllers.home);
```

This is also true when you use it without the slash at the end

(`/:lng`)

**Comment by jamuhl** [comment]
as far i know that's regular behaviour in express. `/something/` allows `/something`. you might try a regex route like `/:lng/*`

**Comment by ApfelUser** [comment]
Hm. I just discovered that you can but anything in `/:lng/` ( Like `/isaduh/team/` ) and it will also render in English.

**Comment by jamuhl** [comment]
anything passed to `/:lng/` will be taken as param. So some invalid language there will fallback to your fallback language. the `/:lng` will not be translated or replaced as all params be kept as params for express -> /:lng will be needed to grab the language.

might optimize that after upcoming version v2 of i18next.

**Comment by jamuhl** [comment]
upcoming v2: http://i18next.github.io/i18next.com/

i18next-node will be replaced by https://github.com/i18next/i18next-express-middleware

PRs welcome
