### ISSUE TITLE
Dinamically add new namespace?

### ISSUE THREAD

**Issue by vekexasia** [i18next/i18next-node#210]
Hello there,

is there a way to add a namespace after .init?

It might be helpful when, for example, the user is in the admin panel and i'd like to load the "admin" namespace on top of the others.

**Comment by jamuhl** [comment]
there is `i18next.loadNamespaces(arrayOfNamespaceStrings, callback)`

**Comment by vekexasia** [comment]
ups i didn't see it in the documentation... thank you.
