### ISSUE TITLE
Question: what is the best practice for i18next-node locales?

### ISSUE THREAD

**Issue by silkentrance** [i18next/i18next-node#211]
I am currently developing a suite of tools for an alternative file format for authoring i18next translation units for use with my own projects and maybe others might find this useful, too.

In the documentation, you sometimes use ``namespace.lang-id.json``

```
{
   'key1' : 'foobar'
}
```

and other times you use this, without specifying a filename

```
{
   'en-US': {
      'translation': {
          'key1' : 'foobar'
      }
   }
}
```

While I reckon that the latter is a shortcut for documentation purposes, I am still wondering what the best practices to laying out your locales directory are.

Could you please add a section on best practices in the documentation?

E.g. 

```
locales/en/translation.json
locales/en/ns1.json
locales/en-US/translation.json
locales/en-US/ns1.json
locales/fr/translation.json
locales/fr/ns1.json
```

vs.

```
locales/translation.en.json
locales/ns1.en.json
locales/translation.en-US.json
locales/ns1.en-US.json
locales/translation.fr.json
locales/ns1.fr.json
```

Considering the default template used in i18next (browser), which is ``locales/__lng__/__ns__.json`` you seem to be in favor of the first alternative, however, you do not seem to define ``translation`` to be default namespace there, while in i18next-node this does seem to be the case.

**Comment by jamuhl** [comment]
both i18next in node.js and browser use `translation` as default namespace.

at our company we use `locales/lng/ns.json` to store jsons in the backend, but we use the dynamicRoute to load them. On the other hand for smaller projects `locales/ns.lng.json` could be as good. There is no real preference.

The given default on i18next is always `locales/lng/ns.json`.

Please be aware of upcoming v2 of i18next: http://i18next.github.io/i18next.com/

Backends will be new separated in own modules and can be added to i18next on demand:
http://i18next.github.io/i18next.com/docs/ -> Getting started
http://i18next.github.io/i18next.com/docs/ecosystem/#backends

eg. path in xhr backend: https://github.com/i18next/i18next-xhr-backend#backend-options

**Comment by jamuhl** [comment]
for the difference of:

```
{
   'key1' : 'foobar'
}
```

vs:

```
{
   'en-US': {
      'translation': {
          'key1' : 'foobar'
      }
   }
}
````

first is what gets loaded from server if loading one file.
second is if loaded by dynamicLoad or added initial as options.resStore.

**Comment by jamuhl** [comment]
v2 is beta now...but will go over to release the next weeks. So i wouldn't but to much effort in v1.

**Comment by silkentrance** [comment]
@jamuhl thanks for your input. perhaps pointing out the fact that ``translation`` is the default namespace in ``18next`` (browser) in the documentation's provided examples would ease up things a bit, i.e. lowering the learning curve a bit?

**Comment by jamuhl** [comment]
options and there defaults are in v2 on own page: http://i18next.github.io/i18next.com/docs/options/

defaultNS: default: 'translation'

**Comment by jamuhl** [comment]
would be very welcome if you could review v2 docs for improvements

**Comment by silkentrance** [comment]
@jamuhl without opening an additional issue, i would propose that before each ``loaded resources`` section in the docs, you present a set of input files including their respective file system based locations, perhaps also promoting the ``locales/lng/ns.json`` best practice?

**Comment by jamuhl** [comment]
done: http://i18next.github.io/i18next.com/translate/

**Comment by silkentrance** [comment]
Great, thank you!
