### ISSUE TITLE
README clarification

### ISSUE THREAD

**Issue by strarsis** [i18next/i18next-node#214]
In README
````
i18next-node can be replaced with:

- i18next
- i18next-express-middleware
````

Does this means i18next-node can be replaced with
i18next _or_ i18next-express-middleware or rather
it can be replaced with
i18next for standalone use and otherwise
i18next _and_ i18next-express-middleware for express apps?

Thank you and
with best regards

**Comment by jamuhl** [comment]
i18next for standalone use and otherwise
i18next and i18next-express-middleware for express apps?

updated readme
