### ISSUE TITLE
Dynamic update app language in React Native using i18next

### ISSUE THREAD

**Issue by kirankjolly** [i18next/i18next-node#217]
I want to create a react native app that should change language while change language in the settings even if we manually not set a language inside the app. I have done manually set language inside the app. If we set it we don't have to set app language according to with the system language.

Without manually set a language, I changed the system language. But the app language is not changing. After refreshing the app the language changed. So I need to change app language without refresh while changing system language.

code below or check this [link](https://stackoverflow.com/questions/52929559/dynamic-update-app-language-in-react-native-using-i18next)

`import i18n from 'i18next';
import { reactI18nextModule } from 'react-i18next';
import locale from 'react-native-locale-detector';
import { AsyncStorage } from 'react-native';
import DeviceInfo from 'react-native-device-info';
import de from './de.json';
import en from './en.json';
import ar from './ar.json';
const STORAGE_KEY = '@APP:languageCode';
const languageDetector = {
  init: Function.prototype,
  type: 'languageDetector',
  async: true,
  detect: async (callback) => {
    const savedDataJSON = await AsyncStorage.getItem(STORAGE_KEY);
    const lng = (savedDataJSON) ? savedDataJSON : null;
    const selectLanguage = lng || locale;
    console.log('detect - selectLanguage:', selectLanguage);
    callback(selectLanguage);
  },
  cacheUserLanguage: () => { }
};

i18n
  .use(languageDetector)
  .use(reactI18nextModule)
  .init({
    fallbackLng: 'en',
    resources: { en, de, ar },
    ns: ['common'],
    defaultNS: 'common',
    debug: true,
    interpolation: {
      escapeValue: false,
    }
  });

export default i18n;`

**Comment by jamuhl** [comment]
you will need to somehow listen to language changes done by system (idk how to do so) and call i18n.changeLanguage: https://www.i18next.com/overview/api#changelanguage

**Comment by kirankjolly** [comment]
I know about i18next.changeLanguage("de-DE");
But i don't know about the events which trigger just after change the system language. Or there any specific way/procedure.

**Comment by jamuhl** [comment]
that's what i say...i maintain react-i18next not react-native -> i have no idea. ---> ask for that on stackoverflow....might be someone knows a module doing events triggering on system language change
