### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by ghost** [i18next/i18next-node#34]
I find YAML to be an excellent translation format since now you can send the translation files to translators and they don't need to know JSON to translate it.

```
Exit: Avsluta
Create: Skapa
```

All my translation files are in yaml and I use https://github.com/nodeca/js-yaml to load them in:

```
var translation = require('locales/en-US.yml')
translation.Exit // => Avsluta
translation.Create // => Skapa
```

Could YAML be supported out of the box so we can have our translation files in YAML instead of JSON?

**Comment by fragsalat** [comment]
Can someone tell me how that works with the latest version of i18next? It seems like this module is depricated and not working anymore.
